"""initial migration

Revision ID: 99ae4fdd5deb
Revises: 
Create Date: 2024-10-02 14:28:59.685198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ae4fdd5deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gov_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('school_zip', sa.Integer(), nullable=True),
    sa.Column('school_state', sa.String(), nullable=True),
    sa.Column('school_city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools')),
    sa.UniqueConstraint('gov_id', name=op.f('uq_schools_gov_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('staff_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('user_relationship', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('expected_grade_level', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('age >= 0', name=op.f('ck_students_ck_age_not_neg')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_signature', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_applications_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_applications_student_id_students')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
